### PR TITLE
Remove unused line in installer

### PR DESCRIPTION
**Pull request by ghost**
Paul's pointless pull request, to get the ball rolling!

### CODE REVIEW

**Comment by fiveseven808** [comment]
Thanks Paul! I'll try to commit something today!

**Comment by gtcode** [comment]
Yo Brian, LMK if you want to hack on it!  I hang around HNL and Kailua often.  Sometimes it's productive to hack away on different projects and keep each other on point.  You clearly have a great deal of skills and the all-important ability to "get it done".  I have a lot of respect for those with an affinity for the GSD method. :)

What a cool project.  Glad to meet you.

**Comment by ghost** [comment]
Looks like we need to move the ball to the top of a hill, get it meta-stable, before getting the ball rolling!

Thusly proposing to standardize upon the following two metaphors, duly applicable:

Get ball to top of hill (meta-stable): Comprehend the code
Get ball rolling: Change the code

**Comment by ghost** [comment]
Interesting search for Phillips related open source code:
https://github.com/search?o=desc&q=phillips&s=stars&type=Repositories&utf8=%E2%9C%93

Thought of that search because I was reading this article:
https://iayanpahwa.github.io/Reverse-Engineering-IoT-Devices/

**Comment by fiveseven808** [comment]
omg it's been like a month already and I haven't done anything lol. 

I'll take your advice and start planning out something to try and get the ball to the top of the hill. 

Very cool looking at what kinds of open source stuff is out there! i'm sad that my project doesn't even make the first few pages lol.

**Comment by ghost** [comment]
yeah dude, standard for open source projects is higher than closed source!

**Comment by fiveseven808** [comment]
woah, i just read that article you sent about the bluetooth bulbs! that's so cool!!!! now i want to build a hue-like api for those bluetooth bulbs! LOL

**Comment by ghost** [comment]
Sounds like fun, going to pursue it?  If so, what are your thoughts to kick off the project?

**Comment by fiveseven808** [comment]
Well the main thought would be to buy a cheap Bluetooth bulb and see if that guys code works automagically. If so then I'll just take a the hue API and try to make a wrapper around the Bluetooth commands :P

First step would be to find a cheap Chinese bulb though!

**Comment by fiveseven808** [comment]
I just figured out how to link to my discord! 
https://discord.gg/YxUusf8

I've no verification set for it right now, would you be interested in brainstorming on that instead of a pull request? lol

**Pull request merged**
